export const MENU_DATA = [
  { url: '/button', title: 'Button', key: '1' },
  { url: '/dialog', title: 'Dialog', key: '2' },
  { url: '/menu', title: 'Menu', key: '3' },
  { url: '/loading', title: 'Loading', key: '4' },
  { url: '/message', title: 'Message', key: '5' },
  { url: '/axios-test', title: 'axios-test', key: '6' },
  { url: '/carousel', title: 'carousel', key: '7' },
  { url: '/editForm', title: 'editForm', key: '8' },
  { url: '/editTable', title: 'editTable', key: '9' },
  { url: '/g6Tree', title: 'g6Tree', key: '10' },
  { url: '/g6BloodLineage', title: 'g6BloodLineage', key: '11' },
  { url: '/selectSearch', title: 'selectSearch', key: '12' },
  { url: '/searchForm', title: 'searchForm', key: '13' },
  { url: '/searchTable', title: 'searchTable', key: '14' },
  { url: '/echartSankey', title: 'echartSankey', key: '15' },
  { url: '/editTextArea', title: 'editTextArea', key: '16' },
];
